package ar.unlu.edu.mvc.modelo;

public enum Evento {
    JUGADOR_AGREGADO,
    CAMBIO_TURNO,
    FIN_TURNO,
    CARTA_AGREGADA_CARNAVAL,
    ULTIMA_RONDA,
    DESCARTAR_DOS_CARTAS,
    RONDA_DESCARTE,
    FIN_JUEGO,
    CARTA_AGREGADA_MANO,



    //probables exceptions
    NO_SE_PUEDE_AGARRAR,
    ELIGIO_CARTA_SALVADA,
    CARTA_MAL_ELEGIDA_CARNAVAL

}
