package ar.unlu.edu.mvc.modelo;

public enum Evento {
    JUEGO_COMENZADO,
    JUGADOR_AGREGADO,
    CAMBIO_TURNO,
    CARTA_TIRADA,
    CARTA_AGREGADA_CARNAVAL,
    CARTA_AGREGADA_MANO,
    FIN_TURNO,
    ULTIMA_RONDA,
    DESCARTAR_DOS_CARTAS,
    RONDA_DESCARTE,
    FIN_JUEGO,



    //probables exceptions
    NO_SE_PUEDE_AGARRAR,
    ELIGIO_CARTA_SALVADA,
    CARTA_MAL_ELEGIDA_CARNAVAL

}
